#language: python, node_js

language: node_js

#python:
#  - "3.7"
node_js:
  - 12

cache:
  yarn: true
  directories:
    - 'node_modules'

services:
  - docker

before_script: npm i -D jest jest-vue-preprocessor babel-jest vue-test-utils
before_script: pip install docker-compose
before_script: npm install -g jest
before_script: npm install --save-dev jest-cli
before_script: yarn add --dev babel-jest @babel/core @babel/preset-env
before_script: yarn global add jest

script:
  - docker-compose run frontend sh -c "cd nuxtproject && yarn test"
  #- docker-compose run backend sh -c "cd djangoproject && python manage.py test && flake8"
