#language: python, node_js

language: node_js

#python:
#  - "3.7"
node_js:
  - 12

services:
  - docker

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - 'node_modules'


# before_script: npm i -D jest jest-vue-preprocessor babel-jest vue-test-utils
# before_script: pip install docker-compose
# before_script: npm install --save-dev docker-compose
# before_script: npm install -g jest
# before_script: npm install --save-dev jest
# before_script: yarn add -D jest
# before_script: yarn add -D @vue/test-utils lodash.clonedeep
# before_script: yarn add --dev babel-jest @babel/core @babel/preset-env


# before_script: npm install -g jest
# before_script: npm install --save-dev jest-cli
# before_script: yarn add @nuxtjs/axios
# before_script: yarn add --dev babel-jest @babel/core @babel/preset-env
# before_script: yarn global add jest
# before_script: yarn add --dev jest

# install:
#   - node -v
#   - npm i -g yarn
#   - yarn

script:
  - docker-compose build
  - docker-compose run frontend sh -c "cd nuxtproject && ls && yarn test"
  #- docker-compose run backend sh -c "cd djangoproject && python manage.py test && flake8"
