language: node_js

node_js:
  - 12

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - docker-compose run frontend sh -c "yarn test"
