language: node_js

node_js:
  - 12

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

cache:
  yarn: true
  directories:
    - 'node_modules'

before_script:
  - docker-compose build
  - docker-compose up -d
  - npm install --save-dev jest-cli
  - yarn add --dev jest

script:
  - docker exec -it frontend ls node_modules

