language: python
python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose
before_script: npm install --save-dev docker-compose

script:
  - docker-compose run backend sh -c "python manage.py test && flake8"