language: node_js

node_js:
  - 12

services:
  - docker

before_script: pip install docker-compose
before_script: npm install --save-dev docker-compose

script:
  - docker-compose run frontend sh -c "cd nuxtproject && yarn test"
