#language: python, node_js

language: node_js

#python:
#  - "3.7"
node_js:
  - 12

cache:
  yarn: true
  directories:
    - 'node_modules'

services:
  - docker

before_script: pip install docker-compose
before_script: npm install --save-dev docker-compose
before_script: npm install -g yarn
before_script: yarn add --dev jest

script:
  - docker-compose run frontend sh -c "cd nuxtproject && yarn test"
  #- docker-compose run backend sh -c "cd djangoproject && python manage.py test && flake8"
