version: '3'

services:

  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./Dockerfiles/frontend/Dockerfile
    tty: true
    command: npm run dev
    ports:
      - '3000:3000'