# version: 2.1
# jobs:
#  build:
#     docker:
#       - image: circleci/node:9.8.0-stretch-browsers
#       - image: circleci/python:3.7
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Docker Compose をインストール
#           command: |
#             curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#             chmod +x ~/docker-compose
#             sudo mv ~/docker-compose /usr/local/bin/docker-compose
#       - run:
#           name: docker-compose build
#           command:
#             docker-compose -f ./docker-compose.yml build
#       - run:
#           name: テスト
#           command: |
#             docker-compose run backend ls
#             docker-compose run backend python manage.py makemigrations




version: 2.1
jobs:
 build:
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:9.6.2
        environment: # environment variables for the Postgres container.
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Compose をインストール
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose build
          command:
            docker-compose -f ./docker-compose.yml build
      - run:
          name: テスト
          command: |
            docker-compose run backend ls
            docker-compose run backend python manage.py migrations

