# version: 2.1
# jobs:
#  build:
#     docker:
#       - image: circleci/node:9.8.0-stretch-browsers
#       - image: circleci/python:3.7
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Docker Compose をインストール
#           command: |
#             curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#             chmod +x ~/docker-compose
#             sudo mv ~/docker-compose /usr/local/bin/docker-compose
#       - run:
#           name: docker-compose build
#           command:
#             docker-compose -f ./docker-compose.yml build
#       - run:
#           name: テスト
#           command: |
#             docker-compose run backend ls
#             docker-compose run backend python manage.py makemigrations




# version: 2.1
# jobs:
#   build:
#     machine: true
#     steps:
#       - checkout
#       - run:
#           name: docker-compose build
#           command:
#             docker-compose -f ./docker-compose.yml build
#       - run:
#           name: テスト
#           command: |
#             docker-compose run backend python manage.py test



version: 2.1
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two